name: Rust Tests

on:
  push:
    branches: [ main  ]
  pull_request:
    branches: [ main  ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Rust
      run: |
        rustup toolchain install stable
        rustup default stable
    - name: Run tests
      run: cargo test --verbose
